{
 "title": "Sinais Vitais",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Status do Paciente (KPIs)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Localização Atual",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "EC_DATA", "rawSql": "SELECT * FROM V_MFR_ATUAL;" }
   ]
  },
  {
   "title": "Status da Iluminação",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "EC_DATA", "rawSql": "SELECT * FROM V_LDR_ATUAL;" }
   ]
  },
  {
   "title": "Estado de Repouso",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "EC_DATA",
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN UPPER(TRIM(COALESCE(local, ''))) = 'BEDROOM' AND valor < 20 THEN 'Dormindo'\r\n    ELSE 'Acordado'\r\n  END AS \"status\"\r\nFROM\r\n  TBL_SENSORES\r\nWHERE\r\n  sensor_id = 202\r\nORDER BY\r\n  data_hora DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Movimentações diárias",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "EC_DATA",
     "rawSql": "\r\nWITH transitions AS (\r\n  SELECT\r\n    TRIM(local) as current_local,\r\n    LAG(TRIM(local), 1, '') OVER (ORDER BY data_hora) AS previous_local\r\n  FROM\r\n    TBL_SENSORES\r\n  WHERE\r\n    DATE(data_hora) = CURDATE() AND\r\n    local IS NOT NULL AND TRIM(local) != ''\r\n)\r\nSELECT\r\n  COUNT(*) AS \"Trocas de Cômodo\"\r\nFROM\r\n  transitions\r\nWHERE\r\n  current_local != previous_local;"
    }
   ]
  },
  {
   "title": "Status de Inatividade",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "EC_DATA",
     "rawSql": "\r\nWITH last_location AS (\r\n    SELECT\r\n        data_hora,\r\n        local\r\n    FROM TBL_SENSORES\r\n    WHERE\r\n        local IS NOT NULL AND TRIM(local) != ''\r\n    ORDER BY data_hora DESC\r\n    LIMIT 1\r\n),\r\nlast_change AS (\r\n    SELECT\r\n        MAX(data_hora) AS last_change_time\r\n    FROM (\r\n        SELECT\r\n            data_hora,\r\n            TRIM(local) as current_local,\r\n            LAG(TRIM(local), 1, '') OVER (ORDER BY data_hora) AS previous_local\r\n        FROM TBL_SENSORES\r\n        WHERE\r\n            data_hora >= NOW() - INTERVAL 1 DAY AND\r\n            local IS NOT NULL AND TRIM(local) != ''\r\n    ) AS transitions\r\n    WHERE\r\n        current_local != previous_local\r\n)\r\nSELECT\r\n    CASE\r\n        \r\n        WHEN lc.last_change_time < NOW() - INTERVAL 2 HOUR AND (HOUR(NOW()) >= 7 AND HOUR(NOW()) < 22) THEN 'Alerta: Inatividade'\r\n        \r\n        -- 3. Se tudo estiver bem\r\n        ELSE 'OK'\r\n    END AS \"status_risco\"\r\nFROM\r\n    last_location ll,\r\n    last_change lc;"
    }
   ]
  },
  { "title": "Sinais Vitais", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Monóxido de carbono",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "EC_DATA", "rawSql": "SELECT * FROM V_MQ_ATUAL;" }
   ]
  },
  {
   "title": "Frequência cardíaca",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "EC_DATA", "rawSql": "SELECT * FROM V_HRS_ATUAL;" }
   ]
  },
  {
   "title": "Temperatura",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "EC_DATA", "rawSql": "SELECT * FROM V_LM_ATUAL;" }
   ]
  },
  {
   "title": "Oxigenação do Sangue",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "EC_DATA", "rawSql": "SELECT * FROM V_MAX_ATUAL;" }
   ]
  },
  {
   "title": "Locais Mais Visitados Hoje",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "EC_DATA",
     "rawSql": "SELECT\r\n  local AS \"Cômodo\",\r\n  COUNT(*) AS \"Número de Visitas\"\r\nFROM (\r\n  SELECT\r\n    local,\r\n    LAG(local, 1, '') OVER (ORDER BY data_hora) AS local_anterior\r\n  FROM\r\n    TBL_SENSORES\r\n  WHERE\r\n    local IS NOT NULL AND local != '' and local != 'Global'\r\n) AS t\r\nWHERE\r\n  local != local_anterior\r\nGROUP BY\r\n  local\r\nORDER BY\r\n  \"Número de Visitas\" DESC;"
    }
   ]
  },
  {
   "title": "Chance de DEC",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "EC_DATA",
     "rawSql": "SELECT chance FROM EC_DATA.TBL_CORRCARDIACA order by data_hora desc LIMIT 1;"
    }
   ]
  },
  { "title": "Comparações", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Situações BPM",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "EC_DATA",
     "rawSql": "SELECT COUNT(situacao), situacao FROM EC_DATA.V_SITUACAO_BPM GROUP BY situacao LIMIT 50 "
    }
   ]
  },
  {
   "title": "Temperatura X Comodo",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "EC_DATA",
     "rawSql": "SELECT local, situacao, valor\r\nFROM (\r\n    SELECT \r\n        local,\r\n        situacao,\r\n        data_hora,\r\n        valor,\r\n        ROW_NUMBER() OVER (PARTITION BY local ORDER BY data_hora DESC) AS rn\r\n    FROM V_TEMPERATURA_POR_COMODO\r\n) t\r\nWHERE rn = 1;"
    }
   ]
  },
  {
   "title": "BPM X Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "dataset": "EC_DATA",
     "rawSql": "SELECT \r\n  data_hora as time,\r\n  bpm as BPM,\r\n  temperatura\r\nFROM EC_DATA.V_BPM_CRAWLER\r\nWHERE $__timeFilter(data_hora)"
    }
   ]
  },
  { "title": "Totem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Monóxido de carbono",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "EC_DATA",
     "rawSql": "SELECT valor AS \"Valor\", data_hora AS \"Data Hora\" FROM EC_DATA.V_MQ7 ORDER BY data_hora ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Luminosidade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ohm" } },
   "targets": [
    {
     "dataset": "EC_DATA",
     "rawSql": "SELECT valor AS \"Valor\", data_hora AS \"Data Hora\" FROM EC_DATA.V_LDR ORDER BY data_hora ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Temperatura do ambiente",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "EC_DATA",
     "rawSql": "SELECT valor AS \"Valor\", data_hora AS \"Data Hora\" FROM EC_DATA.V_LM35 ORDER BY data_hora ASC LIMIT 50 "
    }
   ]
  },
  { "title": "Pulseira", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Frequência cardíaca",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "dataset": "EC_DATA",
     "rawSql": "SELECT valor AS \"Valor\", data_hora AS \"Data Hora\" FROM EC_DATA.V_HRS3300 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Oxigenação do sangue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "dataset": "EC_DATA",
     "rawSql": "SELECT valor AS \"Valor\", data_hora AS \"Data hora\" FROM EC_DATA.V_SP02 ORDER BY data_hora ASC LIMIT 50 "
    }
   ]
  },
  { "title": "Histórico", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Histórico de Alertas",
   "type": "table",
   "description": "A listagem representa todos os alertas registrados pelo sistema de monitoramento.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "dataset": "EC_DATA",
     "rawSql": "SELECT momento_alerta as \"Data/Hora\",\r\n local_ajustado as \"Localização\",\r\n sensor_gerador as \"Sensor Responsável\",\r\n valor_alerta as \"Valor do Alerta\",\r\n classificacao as \"Classificação\",\r\n co as CO, \r\n bpm as BPM,\r\n temperatura as Temperatura,\r\n spo2\r\n FROM EC_DATA.TBL_HISTORICO_ALERTAS_FLATTENED ORDER BY momento_alerta DESC;"
    }
   ]
  }
 ]
}